---
- name: Ensure data directory
  file:
    path="{{ zoomhub_data_path }}"
    owner="{{ admin_user }}"
    group="{{ admin_user }}"
    state=directory

- name: Ensure database permissions
  file:
    path="{{ zoomhub_db_path }}"
    owner="{{ admin_user }}"
    group="{{ admin_user }}"
    state=file
