language: node_js
node_js:
  - '0.10'

# Don't CI feature branches, but note that this *does* CI PR merge commits --
# including before they're made.
branches:
  only:
    - master

notifications:
  webhooks:
    urls:
      - 'https://webhooks.gitter.im/e/5b83f4ce9cca865c832c'
    on_success: change  # options: [always|never|change] default: change
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

env:
  global:
    - secure: "L6vgB5AL91xvQSwsxefY4YXghIzO3ztM3S/A2BCrrGVGCf5NnIYgTZIXOKSNlr2S+UYQMpPhJbvEp2DwTl68hZAquRpS7wB1ad+zQvtFTRgsjeWWIWpLEpOvOHuXROLeEofKQ962aOsPWU91S+3JC8xlpmlo7qjreO8+/ghZfOk="
