language: node_js
node_js:
  - '0.10'

notifications:
  webhooks:
    urls:
      - 'https://webhooks.gitter.im/e/5b83f4ce9cca865c832c'
    on_success: change  # options: [always|never|change] default: change
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
