---

- name: Add FP Complete APT key
  apt_key: keyserver=keyserver.ubuntu.com id=575159689BEFB442 state=present

- name: Determine Ubuntu release
  command: lsb_release -sc
  register: lsb_release

- name: Add FP Complete APT source
  template: src=apt/fpco.list dest=/etc/apt/sources.list.d/fpco.list

- name: apt-get update
  apt: update_cache=yes

- name: Install build tools
  apt: pkg={{ item }} state=present
  with_items:
    - postgresql
    - stack
    - zlib1g-dev

- name: stack update
  command: stack update

- name: stack setup
  command: stack setup

- name: stack install keter
  command: stack install keter
  args:
    creates: ~/.local/bin/keter

- name: Upload `keter` binary to Rackspace CloudFiles
  rax_files_objects:
    container={{ rackspace_cloudfiles_admin_container }}
    region={{ rackspace_cloudfiles_region }}
    method=put
    dest="keter-{{ lsb_release.stdout }}"
    src=~/.local/bin/keter
    username={{ rackspace_username }}
    api_key={{ rackspace_api_key }}
