stanzas:
  - type: webapp
    exec: ../zoomhub
    hosts:
      - 162.242.235.90
      - api.zoom.it
      - api.zoomhub.net
      - next.api.zoomhub.net
      - next.zoomhub.net
      - openzoom.net
      - openzoom.org
      - staging.zoom.it
      - staging.zoomhub.net
      - staging.zoomhub.org
      - teamteam.team
      - www.zoom.it
      - www.zoomhub.net
      - zoom.it
      - zoomhub.net
    env:
      DATA_PATH: '/mnt/datavolume/zoomhub/data'
      DB_PATH: '/mnt/datavolume/zoomhub/data/content.sqlite3'
      HASHIDS_SALT: 'CHANGE-ME-IN-PRODUCTION'
