stanzas:
  - type: webapp
    exec: ../zoomhub
    hosts:
      - api.zoom.it
      - next.api.zoomhub.net
      - next.zoomhub.net
      - openzoom.net
      - openzoom.org
      - staging.zoom.it
      - staging.zoomhub.net
      - staging.zoomhub.org
      - teamteam.team
      - v2.zoom.it
      - v2.zoomhub.net
      - v2.zoomhub.org
      - www.zoom.it
      - zoom.it
    env:
      DATA_PATH: '/mnt/datavolume/zoomhub/data'
      HASHIDS_SALT: 'CHANGE-ME-IN-PRODUCTION'
