---
- stat: path=/opt/splunkforwarder/bin/splunk
  register: splunk_bin

- name: Download Splunk Forwarder from Rackspace CloudFiles
  rax_files_objects:
    container={{ rackspace_cloudfiles_admin_container }}
    region={{ rackspace_cloudfiles_region }}
    method=get
    src=splunkforwarder-6.3.3-f44afce176d0-linux-2.6-amd64.deb
    dest={{ ansible_env.HOME}}
    username={{ rackspace_username }}
    api_key={{ rackspace_api_key }}
  when: splunk_bin.stat.exists == False

- name: Install Splunk
  apt:
    deb="{{ ansible_env.HOME}}/splunkforwarder-6.3.3-f44afce176d0-linux-2.6-amd64.deb"
    state=present

- name: Start Splunk Forwarder
  command: /opt/splunkforwarder/bin/splunk start --accept-license

- name: Ensure Splunk Forwarder auto-starts
  command: /opt/splunkforwarder/bin/splunk enable boot-start

- name: Change Splunk Forwarder password
  command: /opt/splunkforwarder/bin/splunk
          edit user {{ splunk_forwarder_username }}
           -password {{ splunk_forwarder_password }}
           -role admin
           -auth admin:changeme
  ignore_errors: yes

- name: Configure Splunk Forwarder
  command: /opt/splunkforwarder/bin/splunk add forward-server
    {{ splunk_indexer_host }}:{{ splunk_indexer_receiving_port }}
    -auth {{ splunk_forwarder_username }}:{{ splunk_forwarder_password }}
  ignore_errors: yes

- name: Configure Splunk Forwarder as deployment client
  command: /opt/splunkforwarder/bin/splunk set deploy-poll
    {{ splunk_indexer_host }}:{{ splunk_indexer_management_port }}

- name: Restart Splunk
  command: /opt/splunkforwarder/bin/splunk restart
